### ISSUE TITLE
HI bias

### ISSUE THREAD

**Issue by JohnPodczerwinski** [radiocosmology/cora#56]
Hello, 

Suppose I use cora-makesky to generate maps of the HI signal. Will these maps be computed assuming b(z) = 1?

Thanks,
John

**Comment by jrs65** [comment]
Indeed, if you use `cora-makesky` the bias is 1 (see [here](https://github.com/radiocosmology/cora/blob/0b36e06d0c08b012a586b744ca033a8af831c951/cora/signal/corr21cm.py#L178)). You get a bit more flexibility if you use the new `cora.signal.lss` pipeline, so if that's of interest I can send an example of how to use it.

**Comment by JohnPodczerwinski** [comment]
Hi Richard,

Sure, an example of how to use the new pipeline would be great!

thanks,
John

________________________________
